package org.krzywicki.app

import org.krzywicki.app.Configs._
import org.krzywicki.labs.LabsProblem
import org.krzywicki.localsearch._

object LabsSequentialNoLocalSearch extends SequentialConfig with LabsProblem with NoLocalSearch
object LabsSequentialTaboo extends SequentialConfig with LabsProblem with TabooSearch
object LabsSequentialRMHC extends SequentialConfig with LabsProblem with RandomMutationHillClimbing
object LabsSequentialSDLS extends SequentialConfig with LabsProblem with SteepestDescend

object LabsHybridNoLocalSearch extends HybridConfig with LabsProblem with NoLocalSearch
object LabsHybridTaboo extends HybridConfig with LabsProblem with TabooSearch
object LabsHybridRMHC extends HybridConfig with LabsProblem with RandomMutationHillClimbing
object LabsHybridSDLS extends HybridConfig with LabsProblem with SteepestDescend

object LabsConcurrentNoLocalSearch extends ConcurrentConfig with LabsProblem with NoLocalSearch
object LabsConcurrentTaboo extends ConcurrentConfig with LabsProblem with TabooSearch
object LabsConcurrentRMHC extends ConcurrentConfig with LabsProblem with RandomMutationHillClimbing
object LabsConcurrentSDLS extends ConcurrentConfig with LabsProblem with SteepestDescend

